[build]
  command = "npm run build:ignore"
  publish = "dist"

# Ignore TypeScript errors during build
[build.environment]
  NETLIFY_USE_YARN = "false"
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
